"""create video progress table

Revision ID: 0bd8caaf0dd7
Revises: ad2a8caf78df
Create Date: 2024-07-24 13:47:26.052640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bd8caaf0dd7'
down_revision: Union[str, None] = 'ad2a8caf78df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
