"""Change telefono to String

Revision ID: 1146722919fd
Revises: 16f360cc3378
Create Date: 2024-07-05 19:17:56.782286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1146722919fd'
down_revision: Union[str, None] = '16f360cc3378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'telefono',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint('user_genero_fkey', 'user', type_='foreignkey')
    op.drop_constraint('user_rolUsuario_fkey', 'user', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('user_rolUsuario_fkey', 'user', 'rol', ['rolUsuario'], ['idRol'])
    op.create_foreign_key('user_genero_fkey', 'user', 'genero', ['genero'], ['idGenero'])
    op.alter_column('user', 'telefono',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
