"""Initial migration

Revision ID: 16f360cc3378
Revises: 
Create Date: 2024-07-05 17:14:19.887036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16f360cc3378'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('idCategoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('idCategoria')
    )
    op.create_table('genero',
    sa.Column('idGenero', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('genero', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('idGenero')
    )
    op.create_table('rol',
    sa.Column('idRol', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('idRol')
    )
    op.create_table('curso',
    sa.Column('idCurso', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idCategoria', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ultimaActualizacion', sa.Date(), nullable=True),
    sa.Column('calificacion', sa.Float(), nullable=True),
    sa.Column('numEstudiantes', sa.Integer(), nullable=True),
    sa.Column('requisitos', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['idCategoria'], ['categoria.idCategoria'], ),
    sa.PrimaryKeyConstraint('idCurso')
    )
    op.create_table('user',
    sa.Column('idUsuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('passwordEncrypt', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('telefono', sa.Integer(), nullable=True),
    sa.Column('fechaNacimiento', sa.Date(), nullable=True),
    sa.Column('nombreUsuario', sa.String(), nullable=False),
    sa.Column('biografia', sa.Text(), nullable=True),
    sa.Column('genero', sa.Integer(), nullable=False),
    sa.Column('imgPerfilPath', sa.String(), nullable=True),
    sa.Column('rolUsuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genero'], ['genero.idGenero'], ),
    sa.ForeignKeyConstraint(['rolUsuario'], ['rol.idRol'], ),
    sa.PrimaryKeyConstraint('idUsuario'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('nombreUsuario')
    )
    op.create_table('inscripcion',
    sa.Column('idInscripcion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idCurso', sa.Integer(), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('fechaInscripcion', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['idCurso'], ['curso.idCurso'], ),
    sa.ForeignKeyConstraint(['idUsuario'], ['user.idUsuario'], ),
    sa.PrimaryKeyConstraint('idInscripcion')
    )
    op.create_table('video',
    sa.Column('idVideo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idCurso', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('duracionSeg', sa.Integer(), nullable=False),
    sa.Column('autor', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('idPlataforma', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idCurso'], ['curso.idCurso'], ),
    sa.PrimaryKeyConstraint('idVideo')
    )
    op.create_table('aporte',
    sa.Column('idAporte', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idVideo', sa.Integer(), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('numLikes', sa.Integer(), nullable=True),
    sa.Column('fechaAporte', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['idUsuario'], ['user.idUsuario'], ),
    sa.ForeignKeyConstraint(['idVideo'], ['video.idVideo'], ),
    sa.PrimaryKeyConstraint('idAporte')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aporte')
    op.drop_table('video')
    op.drop_table('inscripcion')
    op.drop_table('user')
    op.drop_table('curso')
    op.drop_table('rol')
    op.drop_table('genero')
    op.drop_table('categoria')
    # ### end Alembic commands ###
