"""Add portada column to course

Revision ID: ad2a8caf78df
Revises: 669a5d7ce1eb
Create Date: 2024-07-16 19:21:50.911282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad2a8caf78df'
down_revision: Union[str, None] = '669a5d7ce1eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curso', sa.Column('portada', sa.String(), nullable=True))
    op.drop_column('video', 'idPlataforma')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('idPlataforma', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('curso', 'portada')
    # ### end Alembic commands ###
